### PR TITLE
[doc]Add wss conf

### PR DESCRIPTION
**Pull request by RanMaoyi**

### CODE REVIEW

**Review by JaylinYu — APPROVED** [review]

**Comment by JaylinYu** [comment]
How about 0.18/0.19?

**Comment by JaylinYu** [comment]
plz find @lee-emqx if you need any help of HOCON parser

**Review by JaylinYu — CHANGES_REQUESTED** [review]
Could I use hocon config with wss?

**Comment by RanMaoyi** [comment]
> Could I use hocon config with wss?

Yes, see https://github.com/nanomq/NanoNNG/pull/609

**Review by JaylinYu — APPROVED** [review]

**Pull request merged**
