### PR TITLE
Fixed rest_api compile error on mac.

### PR DESCRIPTION
**Pull request by lee-emqx**

### CODE REVIEW

**Comment by RanMaoyi** [comment]
Maybe this is better
```
diff --git a/nanomq/rest_api.c b/nanomq/rest_api.c
index ad4fc0e..7a4f956 100644
--- a/nanomq/rest_api.c
+++ b/nanomq/rest_api.c
@@ -32,6 +32,7 @@
 #include <stdio.h>
 #include <string.h>
 #include <time.h>
+#include <unistd.h>
 
 #ifdef SUPP_JWT
 #include "l8w8jwt/decode.h"
```

**Review by RanMaoyi — COMMENTED** [review]
Maybe this is better
```
diff --git a/nanomq/rest_api.c b/nanomq/rest_api.c
index ad4fc0e..7a4f956 100644
--- a/nanomq/rest_api.c
+++ b/nanomq/rest_api.c
@@ -32,6 +32,7 @@
 #include <stdio.h>
 #include <string.h>
 #include <time.h>
+#include <unistd.h>
 
 #ifdef SUPP_JWT
 #include "l8w8jwt/decode.h"
```
`warning: implicit declaration of function 'getpid'`

getpid() is declared in <unistd.h> header file.

The warning occurs, if you do not include this header file, to fix the warning include <unistd.h> header file in the program.

**Comment by lee-emqx** [comment]
> Maybe this is better
> 
> ```
> diff --git a/nanomq/rest_api.c b/nanomq/rest_api.c
> index ad4fc0e..7a4f956 100644
> --- a/nanomq/rest_api.c
> +++ b/nanomq/rest_api.c
> @@ -32,6 +32,7 @@
>  #include <stdio.h>
>  #include <string.h>
>  #include <time.h>
> +#include <unistd.h>
>  
>  #ifdef SUPP_JWT
>  #include "l8w8jwt/decode.h"
> `

> Maybe this is better
> 
> ```
> diff --git a/nanomq/rest_api.c b/nanomq/rest_api.c
> index ad4fc0e..7a4f956 100644
> --- a/nanomq/rest_api.c
> +++ b/nanomq/rest_api.c
> @@ -32,6 +32,7 @@
>  #include <stdio.h>
>  #include <string.h>
>  #include <time.h>
> +#include <unistd.h>
>  
>  #ifdef SUPP_JWT
>  #include "l8w8jwt/decode.h"
> ```

**Comment by lee-emqx** [comment]
> Maybe this is better
> 
> ```
> diff --git a/nanomq/rest_api.c b/nanomq/rest_api.c
> index ad4fc0e..7a4f956 100644
> --- a/nanomq/rest_api.c
> +++ b/nanomq/rest_api.c
> @@ -32,6 +32,7 @@
>  #include <stdio.h>
>  #include <string.h>
>  #include <time.h>
> +#include <unistd.h>
>  
>  #ifdef SUPP_JWT
>  #include "l8w8jwt/decode.h"
> ```

This interface is not supported on mac, so this ok.

**Comment by lee-emqx** [comment]
> Maybe this is better
> 
> ```
> diff --git a/nanomq/rest_api.c b/nanomq/rest_api.c
> index ad4fc0e..7a4f956 100644
> --- a/nanomq/rest_api.c
> +++ b/nanomq/rest_api.c
> @@ -32,6 +32,7 @@
>  #include <stdio.h>
>  #include <string.h>
>  #include <time.h>
> +#include <unistd.h>
>  
>  #ifdef SUPP_JWT
>  #include "l8w8jwt/decode.h"
> ```
> 
> `warning: implicit declaration of function 'getpid'`
> 
> getpid() is declared in <unistd.h> header file.
> 
> The warning occurs, if you do not include this header file, to fix the warning include <unistd.h> header file in the program.


This interface is only supported on linux, so on mac the function that call getpid is useless.

**Review by JaylinYu — APPROVED** [review]

**Comment by JaylinYu** [comment]
Failed CI tls needs a deep look

**Pull request merged**
