### PR TITLE
Add hybrid bridger supported

### PR DESCRIPTION
**Pull request by wanghaEMQ**

### CODE REVIEW

**Review by lee-emqx — APPROVED** [review]

**Review by JaylinYu — CHANGES_REQUESTED** [review]
not switchable when disable disconnect event

**Review by JaylinYu — APPROVED** [review]

**Review by wanghaEMQ — COMMENTED** [review]
LGTM!

**Comment by JaylinYu** [comment]
need to work with https://github.com/nanomq/NanoNNG/pull/306

**Review by wanghaEMQ — COMMENTED** [review]
LGTM!

**Pull request merged**
