### PR TITLE
Add AUR package

### PR DESCRIPTION
**Pull request by taotieren**
AUR: https://aur.archlinux.org/pkgbase/nanomq-git

### CODE REVIEW

**Comment by JaylinYu** [comment]
Sure！ Your help is highly appreciated!
Any chance we could know about the download numbers?

**Comment by taotieren** [comment]
> Sure！ Your help is highly appreciated! Any chance we could know about the download numbers?

Use yay-S nanomq-git users to automatically download source code, compile, and install (this is how AUR works)

**Review by JaylinYu — APPROVED** [review]

**Comment by JaylinYu** [comment]
BTW how to make arch linux version always sync with github?

**Comment by JaylinYu** [comment]
> > Sure！ Your help is highly appreciated! Any chance we could know about the download numbers?
> 
> Use yay-S nanomq-git users to automatically download source code, compile, and install (this is how AUR works)

I mean, the number of how many times nanomq has been downloaded at arch linux

**Comment by taotieren** [comment]
> BTW how to make arch linux version always sync with github?

1. By using the latest version number of push on my side, users will receive updates. 
2. Users update locally by themselves

**Comment by taotieren** [comment]
> > > Sure！ Your help is highly appreciated! Any chance we could know about the download numbers?
> > 
> > 
> > Use yay-S nanomq-git users to automatically download source code, compile, and install (this is how AUR works)
> 
> I mean, the number of how many times nanomq has been downloaded at arch linux

Sorry, I can't see the downloads directly in the background, but you can get the corresponding downloads through a third party or an official monitoring platform.

https://wiki.archlinux.org/title/Arch_User_Repository

https://repology.org/project/nanomq/packages

https://github.com/archlinux/aur/tree/nanomq-git

**Pull request merged**
