### PR TITLE
Re-factor bridging mechanism step 1

### PR DESCRIPTION
**Pull request by JaylinYu**

### CODE REVIEW

**Comment by JaylinYu** [comment]
need to work with https://github.com/nanomq/NanoNNG/pull/166.
@alvin1221  please finish the config file reading part.

**Comment by JaylinYu** [comment]
related to #681

**Comment by JaylinYu** [comment]
be aware this breaks HTTP rest API (print all config)
and the fini func of bridge_conf is not finished yet

**Review by lee-emqx — APPROVED** [review]

**Comment by JaylinYu** [comment]
duplicated with #706

**Pull request closed without merging**
