### PR TITLE
nanomq support webhook，but there is no example

### PR DESCRIPTION
**Pull request by huienming**
I know nanomq support webhook,but I can not find an example.
I use emqx webhook program to work with nanomq and got an error.

io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception: Unexpected HTTP/1.x request: POST

Anyone can give me a suggest?

### CODE REVIEW

**Comment by JaylinYu** [comment]
I have a Chinese version example of webhook, is that work for ou?

**Comment by Hermann0222** [comment]
> I have a Chinese version example of webhook, is that work for ou?
I would like to get one too.

**Comment by Hermann0222** [comment]
> I have a Chinese version example of webhook, is that work for ou?

I would like to get one too.

**Comment by JaylinYu** [comment]
https://www.emqx.com/zh/blog/nanomq-newsletter-202205
while I am working on other stuff. plz have a look on this

**Pull request closed without merging**
