### PR TITLE
Rewrite get/update config rest APIs & support hot update for some fields.

### PR DESCRIPTION
**Pull request by alvin1221**

### CODE REVIEW

**Comment by alvin1221** [comment]
related to https://github.com/nanomq/NanoNNG/pull/312

**Review by JaylinYu — APPROVED** [review]

**Comment by JaylinYu** [comment]
why all CI failed

**Comment by alvin1221** [comment]
> why all CI failed

just need to rebase master

**Review by JaylinYu — APPROVED** [review]

**Comment by JaylinYu** [comment]
lets split it into multiple PRs to make sb happy

**Pull request merged**
