### PR TITLE
Rule engin support sqlite persistence.

### PR DESCRIPTION
**Pull request by lee-emqx**

### CODE REVIEW

**Review by JaylinYu — APPROVED** [review]

**Comment by JaylinYu** [comment]
better fix the CodeQL first

**Comment by lee-emqx** [comment]
> better fix the CodeQL first

It's because of sqlite3, not included by my code.

**Comment by lee-emqx** [comment]
This pr is based on #660. This should not be merged if #660 not merged.

**Review by wanghaEMQ — APPROVED** [review]

**Review by JaylinYu — APPROVED** [review]
plz move rule logic out from handle_pub, put them into SEND state

**Pull request merged**
