### PR TITLE
Add SIGTERM handler.

### LINKED ISSUE #1062: The broker does not seem to handle SIGTERM properly.
**Describe the bug**

**Expected behavior**

**Actual Behavior**
Describe what occurred.

**To Reproduce**
If possible include actual reproduction test code here.
Minimal C test cases are perferred.

** Environment Details **
 - NanoMQ version
 - Operating system and version
 - Compiler and language used
 - testing scenario

**Client SDK**
If possible include the mqtt sdk you used to connect to nanomq
Minimal C test cases are perferred.

**Additional context**

### PR DESCRIPTION
**Pull request by lee-emqx**
Fixed #1062

### CODE REVIEW

**Review by RanMaoyi — APPROVED** [review]

**Review by wanghaEMQ — APPROVED** [review]

**Review by OdyWayne — APPROVED** [review]

**Review by JaylinYu — APPROVED** [review]
how about sigmask?

**Comment by JaylinYu** [comment]
win packaging broken

**Comment by JaylinYu** [comment]
DCO is not signed

**Review by JaylinYu — CHANGES_REQUESTED** [review]
DCO
WIn

**Pull request closed without merging**
